In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
from pathlib import Path
from IPython.display import display
pd.options.display.max_columns = None

In [3]:
# Load DataFrame for 2023 listings
listings_big_df23 = pd.read_csv("../airbnb_listings_oct_1_2023.csv.gz")
l_df23 = listings_big_df23.copy()

In [4]:
l_df23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38792 entries, 0 to 38791
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            38792 non-null  int64
 1   listing_url                                   38792 non-null  object
 2   scrape_id                                     38792 non-null  int64
 3   last_scraped                                  38792 non-null  object
 4   source                                        38792 non-null  object
 5   name                                          38792 non-null  object
 6   description                                   38223 non-null  object
 7   neighborhood_overview                         22556 non-null  object
 8   picture_url                                   38792 non-null  object
 9   host_id                                       38792 non-null  int64
 10  host_url                                      38792 non-null  object
 11  host_name                                     38787 non-null  object
 12  host_since                                    38787 non-null  object
 13  host_location                                 30515 non-null  object
 14  host_about                                    21643 non-null  object
 15  host_response_time                            25618 non-null  object
 16  host_response_rate                            25618 non-null  object
 17  host_acceptance_rate                          26888 non-null  object
 18  host_is_superhost                             38537 non-null  object
 19  host_thumbnail_url                            38787 non-null  object
 20  host_picture_url                              38787 non-null  object
 21  host_neighbourhood                            31040 non-null  object
 22  host_listings_count                           38787 non-null  float64
 23  host_total_listings_count                     38787 non-null  float64
 24  host_verifications                            38787 non-null  object
 25  host_has_profile_pic                          38787 non-null  object
 26  host_identity_verified                        38787 non-null  object
 27  neighbourhood                                 22557 non-null  object
 28  neighbourhood_cleansed                        38792 non-null  object
 29  neighbourhood_group_cleansed                  38792 non-null  object
 30  latitude                                      38792 non-null  float64
 31  longitude                                     38792 non-null  float64
 32  property_type                                 38792 non-null  object
 33  room_type                                     38792 non-null  object
 34  accommodates                                  38792 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                38750 non-null  object
 37  bedrooms                                      21892 non-null  float64
 38  beds                                          38129 non-null  float64
 39  amenities                                     38792 non-null  object
 40  price                                         38792 non-null  object
 41  minimum_nights                                38792 non-null  int64
 42  maximum_nights                                38792 non-null  int64
 43  minimum_minimum_nights                        38792 non-null  int64
 44  maximum_minimum_nights                        38792 non-null  int64
 45  minimum_maximum_nights                        38792 non-null  int64
 46  maximum_maximum_nights                        38792 non-null  int64
 47  minimum_nights_avg_ntm                        38792 non-null  float64
 48  maximum_nights_avg_ntm                        38792 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              38792 non-null  object
 51  availability_30                               38792 non-null  int64
 52  availability_60                               38792 non-null  int64
 53  availability_90                               38792 non-null  int64
 54  availability_365                              38792 non-null  int64
 55  calendar_last_scraped                         38792 non-null  object
 56  number_of_reviews                             38792 non-null  int64
 57  number_of_reviews_ltm                         38792 non-null  int64
 58  number_of_reviews_l30d                        38792 non-null  int64
 59  first_review                                  28440 non-null  object
 60  last_review                                   28440 non-null  object
 61  review_scores_rating                          28445 non-null  float64
 62  review_scores_accuracy                        28030 non-null  float64
 63  review_scores_cleanliness                     28040 non-null  float64
 64  review_scores_checkin                         28026 non-null  float64
 65  review_scores_communication                   28034 non-null  float64
 66  review_scores_location                        28023 non-null  float64
 67  review_scores_value                           28024 non-null  float64
 68  license                                       2939 non-null   object
 69  instant_bookable                              38792 non-null  object
 70  calculated_host_listings_count                38792 non-null  int64
 71  calculated_host_listings_count_entire_homes   38792 non-null  int64
 72  calculated_host_listings_count_private_rooms  38792 non-null  int64
 73  calculated_host_listings_count_shared_rooms   38792 non-null  int64
 74  reviews_per_month                             28440 non-null  float64
dtypes: float64(18), int64(21), object(36)
memory usage: 22.2+ MB

In [5]:
l_df23.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [6]:
# Drop null columns
l_df23.drop(labels= ["bathrooms","calendar_updated"], axis=1, inplace=True)
len(l_df.columns)

NameError: name 'l_df' is not defined

In [7]:
l_df23.head(3)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,9630344,https://www.airbnb.com/rooms/9630344,20231001204715,2023-10-02,city scrape,Rental unit in Brooklyn · ★4.80 · 1 bedroom ·...,Enjoy your own private bedroom in our 2 bedroo...,Easy access to subway. Trendy and yet quiet.,https://a0.muscache.com/pictures/496cf3f1-7d0d...,47783628,https://www.airbnb.com/users/show/47783628,Tiffannie,2015-10-30,"New York, NY",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/5c087...,https://a0.muscache.com/im/pictures/user/5c087...,NaN,1.0,2.0,"['email', 'phone']",t,f,"Brooklyn , New York, United States",Bushwick,Brooklyn,40.68457,-73.91181,Private room in rental unit,Private room,1,1 shared bath,NaN,1.0,"[""Body soap"", ""Dryer"", ""Refrigerator"", ""Wifi"",...",$65.00,30,30,30,30,30,30,30.0,30.0,t,29,59,89,364,2023-10-02,5,0,0,2016-08-14,2018-04-30,4.8,4.6,5.0,5.0,5.0,4.8,5.0,NaN,f,1,0,1,0,0.06
1,3533741,https://www.airbnb.com/rooms/3533741,20231001204715,2023-10-02,previous scrape,Rental unit in New York · 1 bedroom · 1 bed · ...,Come stay in the heart of historic Hells Kitch...,NaN,https://a0.muscache.com/pictures/45157664/862a...,17791294,https://www.airbnb.com/users/show/17791294,Taylor,2014-07-07,"New York, NY",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/e204b...,https://a0.muscache.com/im/pictures/user/e204b...,Hell's Kitchen,1.0,1.0,"['email', 'phone']",t,t,NaN,Hell's Kitchen,Manhattan,40.76878,-73.98719,Private room in rental unit,Private room,2,1 bath,1.0,1.0,"[""Smoke alarm"", ""Kitchen"", ""Air conditioning"",...",$110.00,30,1125,30,30,1125,1125,30.0,1125.0,f,0,0,0,0,2023-10-02,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
2,9731039,https://www.airbnb.com/rooms/9731039,20231001204715,2023-10-02,previous scrape,Rental unit in Queens · Studio · 1 bed · 1 bath,Studio Apartment in the heart of Sunnyside: of...,NaN,https://a0.muscache.com/pictures/81a96b92-d357...,50213378,https://www.airbnb.com/users/show/50213378,Mark,2015-11-30,"New York, NY",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/65d77...,https://a0.muscache.com/im/pictures/user/65d77...,Sunnyside,1.0,1.0,"['email', 'phone']",t,f,NaN,Sunnyside,Queens,40.74343,-73.91865,Entire rental unit,Entire home/apt,1,1 bath,NaN,1.0,"[""Smoke alarm"", ""Kitchen"", ""Washer"", ""TV"", ""Ai...",$99.00,30,1125,30,30,1125,1125,30.0,1125.0,t,0,0,0,0,2023-10-02,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [8]:
# Include only the columns we want
l_df23 = l_df23[['id',"host_id","host_listings_count","neighbourhood_cleansed", \
            "neighbourhood_group_cleansed","latitude","longitude","property_type", \
            "room_type","accommodates","amenities","minimum_nights","minimum_minimum_nights", \
            "review_scores_rating", "review_scores_location","license","reviews_per_month"]]

l_df23.head()

,id,host_id,host_listings_count,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,amenities,minimum_nights,minimum_minimum_nights,review_scores_rating,review_scores_location,license,reviews_per_month
0,9630344,47783628,1.0,Bushwick,Brooklyn,40.68457,-73.91181,Private room in rental unit,Private room,1,"[""Body soap"", ""Dryer"", ""Refrigerator"", ""Wifi"",...",30,30,4.80,4.80,NaN,0.06
1,3533741,17791294,1.0,Hell's Kitchen,Manhattan,40.76878,-73.98719,Private room in rental unit,Private room,2,"[""Smoke alarm"", ""Kitchen"", ""Air conditioning"",...",30,30,NaN,NaN,NaN,NaN
2,9731039,50213378,1.0,Sunnyside,Queens,40.74343,-73.91865,Entire rental unit,Entire home/apt,1,"[""Smoke alarm"", ""Kitchen"", ""Washer"", ""TV"", ""Ai...",30,30,NaN,NaN,NaN,NaN
3,21736164,4298654,1.0,Bedford-Stuyvesant,Brooklyn,40.68180,-73.93121,Entire rental unit,Entire home/apt,2,"[""Smoke alarm"", ""Kitchen"", ""Shampoo"", ""Long te...",45,45,5.00,5.00,NaN,0.03
4,22280002,67373899,1.0,Bedford-Stuyvesant,Brooklyn,40.68209,-73.94279,Entire rental unit,Entire home/apt,4,"[""Clothing storage: closet and dresser"", ""Micr...",30,30,4.98,4.94,NaN,1.26

In [9]:
l_df23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38792 entries, 0 to 38791
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            38792 non-null  int64
 1   host_id                       38792 non-null  int64
 2   host_listings_count           38787 non-null  float64
 3   neighbourhood_cleansed        38792 non-null  object
 4   neighbourhood_group_cleansed  38792 non-null  object
 5   latitude                      38792 non-null  float64
 6   longitude                     38792 non-null  float64
 7   property_type                 38792 non-null  object
 8   room_type                     38792 non-null  object
 9   accommodates                  38792 non-null  int64
 10  amenities                     38792 non-null  object
 11  minimum_nights                38792 non-null  int64
 12  minimum_minimum_nights        38792 non-null  int64
 13  review_scores_rating          28445 non-null  float64
 14  review_scores_location        28023 non-null  float64
 15  license                       2939 non-null   object
 16  reviews_per_month             28440 non-null  float64
dtypes: float64(6), int64(5), object(6)
memory usage: 5.0+ MB

In [10]:
# export file
filepath = Path('../listings_oct_2023_clean.csv')  
l_df23.to_csv(filepath)

In [11]:
# import file for listings 2022
listings_big_df22 = pd.read_csv("../airbnb_listings_oct_4_2022.csv.gz", low_memory=False)

In [12]:
l_df22 = listings_big_df22.copy()

In [13]:
# Drop null columns
l_df22.drop(labels= ["bathrooms","calendar_updated"], axis=1, inplace=True)
len(l_df22.columns)

73

In [14]:
# Include only the columns we want
l_df22 = l_df22[['id',"host_id","host_listings_count","neighbourhood_cleansed", \
            "neighbourhood_group_cleansed","latitude","longitude","property_type", \
            "room_type","accommodates","amenities","minimum_nights","minimum_minimum_nights", \
            "review_scores_rating", "review_scores_location","license","reviews_per_month"]]

l_df22.head()

,id,host_id,host_listings_count,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,amenities,minimum_nights,minimum_minimum_nights,review_scores_rating,review_scores_location,license,reviews_per_month
0,2539,2787,9.0,Kensington,Brooklyn,40.64529,-73.97238,Private room in rental unit,Private room,2,"[""Essentials"", ""Wifi"", ""Heating"", ""Hangers"", ""...",30,30.0,4.89,4.75,NaN,0.11
1,2595,2845,6.0,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1,"[""Essentials"", ""Wifi"", ""Heating"", ""Hangers"", ""...",30,30.0,4.68,4.81,NaN,0.31
2,5121,7356,2.0,Bedford-Stuyvesant,Brooklyn,40.68535,-73.95512,Private room in rental unit,Private room,2,"[""Wifi"", ""Heating"", ""Long term stays allowed"",...",30,30.0,4.52,4.47,NaN,0.31
3,5136,7378,1.0,Sunset Park,Brooklyn,40.66265,-73.99454,Entire rental unit,Entire home/apt,4,"[""HDTV with HBO Max, standard cable, Roku, Net...",21,21.0,5.00,4.67,NaN,0.03
4,45935,204586,1.0,Mott Haven,Bronx,40.80635,-73.92201,Private room in rental unit,Private room,1,"[""Essentials"", ""Smoke alarm"", ""Heating"", ""Wifi...",30,30.0,NaN,NaN,NaN,NaN

In [15]:
l_df22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40545 entries, 0 to 40544
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            40545 non-null  int64
 1   host_id                       40545 non-null  int64
 2   host_listings_count           40522 non-null  float64
 3   neighbourhood_cleansed        40545 non-null  object
 4   neighbourhood_group_cleansed  40545 non-null  object
 5   latitude                      40545 non-null  float64
 6   longitude                     40545 non-null  float64
 7   property_type                 40545 non-null  object
 8   room_type                     40545 non-null  object
 9   accommodates                  40545 non-null  int64
 10  amenities                     40545 non-null  object
 11  minimum_nights                40545 non-null  int64
 12  minimum_minimum_nights        40531 non-null  float64
 13  review_scores_rating          32155 non-null  float64
 14  review_scores_location        31689 non-null  float64
 15  license                       5 non-null      object
 16  reviews_per_month             32155 non-null  float64
dtypes: float64(7), int64(4), object(6)
memory usage: 5.3+ MB

In [16]:
# export file
filepath = Path('../listings_oct_2022_clean.csv')  
l_df22.to_csv(filepath)